### PR TITLE
Add more app colors

### PR DESCRIPTION
**Pull request by mmlumba**
Adds certification and default logo colors and modifies hearing logo color to a hex code.
Connects https://github.com/department-of-veterans-affairs/caseflow/issues/4402

### CODE REVIEW

**Comment by nickheiner-usds** [comment]
What is the point of adding these colors if they're not used anywhere?

**Comment by mmlumba** [comment]
I thought you made it a point to use this repo for colors whenever possible. This PR just takes the values from [AppConstants.js](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/constants/AppConstants.js) to this repo.

**Comment by mmlumba** [comment]
@nickheiner-usds Are you ok with me merging in these colors or do you want me to leave these colors in AppConstants and close the PR?

**Comment by mmlumba** [comment]
Closing because "The logo colors don't actually belong in caseflow-frontend-toolkit, because they are only used in Caseflow." -nth2018

**Pull request closed without merging**
